apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: armanhasan005/ai-task-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/ai_task_platform
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_QUEUE_NAME
              value: task_queue
            - name: JWT_SECRET
              value: myverysecretjwtkey
            - name: JWT_REFRESH_SECRET
              value: myverysecretrefreshkey
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
