services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: ai_task_platform
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass redispassword
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:adminpassword@mongodb:27017/ai_task_platform?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_QUEUE_NAME=task_queue
      - JWT_SECRET=myverysecretjwtkey
      - JWT_REFRESH_SECRET=myverysecretrefreshkey

  worker:
    build: ./worker
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://admin:adminpassword@mongodb:27017/ai_task_platform?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_QUEUE_NAME=task_queue
    deploy:
      replicas: 2

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
